### ISSUE TITLE
site - Add "Visiting Boston"/"Attending" page

### ISSUE THREAD

**Issue by GuidoS** [AvidGeo/foss4g2017-dev#10]
For now we need a place to put:

- hotel pricing and link
- some extra curricular

**Comment by MassGIS** [comment]
Would it help at all if I took the essential source in the middle for https://avidgeo.github.io/foss4g2017-dev/attending/ and made a copy and converted the wireframes I mocked up for Extracurrucular and Visiting Boston to that type of source?  I would be doing the grunt work of converting the wireframe to HTML but I wouldn't be modifying the actual staging site.  Then maybe only the web site admins would need to copy and paste?  Just thinking of a way to help while I have some time...

**Comment by GuidoS** [comment]
You can copy the text out of the attending, it's put together with markdown, so you can edit with the online editor: http://dillinger.io/

Then feel free to share the output here.. ;)

**Comment by MassGIS** [comment]
Would you like me to upload photos into the images directory here?  If so it appears I'll need push access.

**Comment by MassGIS** [comment]
Attaching extracurriculars.txt which is really .md
It could get appended to the Attending index.md perhaps
[extracurriculars.txt](https://github.com/AvidGeo/foss4g2017-dev/files/758787/extracurriculars.txt)
![1024px-harpoon_brewery _boston_ma](https://cloud.githubusercontent.com/assets/10077576/22708045/cbaf4c5c-ed42-11e6-92b4-837686d60cda.jpg)
![world_trade_center_from_water](https://cloud.githubusercontent.com/assets/10077576/22708049/ccf58fe0-ed42-11e6-8f26-eaa650791aee.JPG)
![neaq_collage](https://cloud.githubusercontent.com/assets/10077576/22708050/ce06b7ce-ed42-11e6-8be5-265e40f84991.png)

**Comment by MassGIS** [comment]
[extracurriculars.txt](https://github.com/AvidGeo/foss4g2017-dev/files/758795/extracurriculars.txt)

making some titles a little smaller

**Comment by MassGIS** [comment]
[visiting_boston.txt](https://github.com/AvidGeo/foss4g2017-dev/files/759173/visiting_boston.txt)

actually an .md

photos referenced:

![charles_river_stand_up_paddleboards](https://cloud.githubusercontent.com/assets/10077576/22713667/71f7102c-ed57-11e6-96cf-19c25bf4ee91.jpg)
![charles_river_kayaks_1](https://cloud.githubusercontent.com/assets/10077576/22713668/71f706d6-ed57-11e6-8582-52e73243df31.jpg)
![charles_river_from_kendall_duck_boat_1](https://cloud.githubusercontent.com/assets/10077576/22713665/71f661fe-ed57-11e6-8a7e-ad6f2b20ccef.jpg)
![brewer_fountain_boston_common_2](https://cloud.githubusercontent.com/assets/10077576/22713669/71f9ac74-ed57-11e6-9bdc-5fd9205b12fb.jpg)
![bpl_2](https://cloud.githubusercontent.com/assets/10077576/22713664/71f65b82-ed57-11e6-9b16-f5d394a067a3.jpg)
![boston_public_market_cheese_1](https://cloud.githubusercontent.com/assets/10077576/22713666/71f66046-ed57-11e6-96a4-85d9e89cf45a.jpg)
![boston_public_market_4](https://cloud.githubusercontent.com/assets/10077576/22713671/71ffbba0-ed57-11e6-9bbb-d8b8111f3ecd.jpg)
![boston_harborwalk](https://cloud.githubusercontent.com/assets/10077576/22713672/72012d32-ed57-11e6-93fc-922447f6f446.jpg)
![biker](https://cloud.githubusercontent.com/assets/10077576/22713673/720235a6-ed57-11e6-96b8-645e6a13e3f4.jpg)
![tea_party_museum](https://cloud.githubusercontent.com/assets/10077576/22713670/71ff94c2-ed57-11e6-9b71-9d5a08e0dd45.jpg)
![swan_boat](https://cloud.githubusercontent.com/assets/10077576/22713675/72052f22-ed57-11e6-8a8b-14909a1de87c.jpg)
![sailboats_charles_river](https://cloud.githubusercontent.com/assets/10077576/22713674/72029442-ed57-11e6-8302-3da33761ca00.jpg)
![red_sox_field](https://cloud.githubusercontent.com/assets/10077576/22713676/72082966-ed57-11e6-8be6-557bb0a53161.jpg)
![red_line](https://cloud.githubusercontent.com/assets/10077576/22713679/72095b2e-ed57-11e6-9426-590d5bd143ae.jpg)
![quincy_market_1](https://cloud.githubusercontent.com/assets/10077576/22713680/720bb4be-ed57-11e6-8dc1-7628f7d600f2.jpg)
![public_garden_path](https://cloud.githubusercontent.com/assets/10077576/22713677/72092654-ed57-11e6-8b9b-6bba5aaad6bc.jpg)
![public_garden_bridge](https://cloud.githubusercontent.com/assets/10077576/22713678/72092fa0-ed57-11e6-8d46-ef5187283091.jpg)
![paul_revere_house](https://cloud.githubusercontent.com/assets/10077576/22713681/7210c526-ed57-11e6-9254-e5b578cff4a5.jpg)
![orange_line](https://cloud.githubusercontent.com/assets/10077576/22713686/72183bbc-ed57-11e6-979d-4c185543f34d.jpg)
![old_north_church](https://cloud.githubusercontent.com/assets/10077576/22713685/72158a84-ed57-11e6-8725-34a0ca29f119.jpg)
![north_end_mikes_pastry_2](https://cloud.githubusercontent.com/assets/10077576/22713683/721471f8-ed57-11e6-8a8a-b54faf0c843e.JPG)
![hubway_1](https://cloud.githubusercontent.com/assets/10077576/22713682/7211fc2a-ed57-11e6-8e21-010f8f0da65d.jpg)
![harvard_u_gate](https://cloud.githubusercontent.com/assets/10077576/22713684/72156680-ed57-11e6-93dd-f38d4d6d0f00.jpg)
![harvard_u_building](https://cloud.githubusercontent.com/assets/10077576/22713690/721f6fcc-ed57-11e6-942e-93c78f69ea61.jpg)
![harvard_sq_street](https://cloud.githubusercontent.com/assets/10077576/22713688/721e275c-ed57-11e6-8f59-00232715a72b.jpg)
![harvard_sq_news](https://cloud.githubusercontent.com/assets/10077576/22713687/721dfe26-ed57-11e6-963f-c01f7df0ee9a.jpg)
![harbor_tour_islands](https://cloud.githubusercontent.com/assets/10077576/22713689/721e99e4-ed57-11e6-8a7d-c7991006e282.jpg)
![harbor_tour_37](https://cloud.githubusercontent.com/assets/10077576/22713691/721fc152-ed57-11e6-9303-d494ea195284.jpg)
![greenway_flower](https://cloud.githubusercontent.com/assets/10077576/22713692/722020de-ed57-11e6-8ce8-78022e123589.jpg)
![granary_burial](https://cloud.githubusercontent.com/assets/10077576/22713693/7226e3d8-ed57-11e6-86a4-380367b2052b.jpg)
![frog_pond_3](https://cloud.githubusercontent.com/assets/10077576/22713696/7229bdf6-ed57-11e6-8c04-ab088d21a705.jpg)
![freedom_trail](https://cloud.githubusercontent.com/assets/10077576/22713697/7230ddd4-ed57-11e6-9071-e5559a4526ee.jpg)
![faneuil_hall_2](https://cloud.githubusercontent.com/assets/10077576/22713694/7228e50c-ed57-11e6-8f5a-9e6cfaa3eb36.jpg)
![dock_charles_river_2](https://cloud.githubusercontent.com/assets/10077576/22713695/72299754-ed57-11e6-9679-b26a65c7dfab.jpg)

**Comment by GuidoS** [comment]
https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Comment by GuidoS** [comment]
Will let @MassGIS have a crack at making a pull request.
