### ISSUE TITLE
Add "Follow on Facebook" info on the main page

### ISSUE THREAD

**Issue by MassGIS** [AvidGeo/foss4g2017-dev#13]
On the main page there is a "Follow on Twitter" in the lower right.
At this point we could add a "Follow on Facebook"
Link is http://www.facebook.com/foss4g2017

**Comment by GuidoS** [comment]
Can you put together a photoshoped image of how you would like this to look? Thanks @MassGIS

**Comment by MassGIS** [comment]
![facebook_mockup](https://cloud.githubusercontent.com/assets/10077576/22073924/b2aad376-dd74-11e6-8c13-c7bf8f7543a5.png)

**Comment by MassGIS** [comment]
Something like the above (but grey to match instead of black?)  The f is 
![facebook_icon](https://cloud.githubusercontent.com/assets/10077576/22073972/d221744e-dd74-11e6-808c-9aaa5f3d6aca.png)

**Comment by GuidoS** [comment]
will address in next iteration.. ;)

**Comment by GuidoS** [comment]
Will work with @MassGIS on this when ready
