### ISSUE TITLE
Add links to keynote speakers on main page

### ISSUE THREAD

**Issue by MassGIS** [AvidGeo/foss4g2017-dev#14]
On the main page there is no easy way to get more info about the keynote speakers.  How about we add some links?  Suggestions below:

Holly St. Clair
   link her name to https://www.linkedin.com/in/hollystclair
   link "Commonwealth of Massachusetts" to http://www.mass.gov/anf/research-and-tech/oversight-agencies/itd/

Paul Ramsey
    link his name to https://ca.linkedin.com/in/paul-ramsey-717134
    link "CARTO" to https://carto.com/

Dr. Richard Stallman
    link his name to https://en.wikipedia.org/wiki/Richard_Stallman
    link "Free Software Foundation" to http://www.fsf.org/

**Comment by calvinmetcalf** [comment]
not sure about the linkedin links as they go strait to a login if your not logged in, the employer links make sense, maybe we should reach out to HSC and PR about preferred site to link to?
