### ISSUE TITLE
Sponsor page text align left?

### ISSUE THREAD

**Issue by gzambotti** [AvidGeo/foss4g2017-dev#16]
The sponsor page has text content align to the left. I am not sure if it is intentional or is a wrong setting; but it's different from the other pages.

**Comment by gzambotti** [comment]
About page has the same setting. Text align to the left.

**Comment by GuidoS** [comment]
It is showing up as align left for me, can you please take a screen shot if this is still an issue. Thanks @gzambotti

**Comment by gzambotti** [comment]
The text on sponsor and about page have a class name "**inner-wrap**", but the text on register page has a class named "**section**"; this is why the register page show up align to the center, while the sponsor and about page show up align to the left. It is not a big deal, so close the issue if you think is not beneficial to fix it; opposite change the class name from "inner-wrap" to "section".

**Comment by GuidoS** [comment]
@gzambotti yes, I think that the main page is the only page that should be aligned center. Thank you for calling this out as a potential issue... makes me sure there is not some larger thing that someone did not see. ;)
