### ISSUE TITLE
wordsmithing on sponsorship

### ISSUE THREAD

**Issue by cjacqz** [AvidGeo/foss4g2017-dev#23]
This is just wordsmithing, but I felt that these paragraphs were so important and could be tightened up just a little.  Suggested text:

The FOSS4G Boston 2017 Sponsorship Committee has created a variety of sponsorship opportunities for the Boston event. Sponsoring FOSS4G, unlike other conferences, is not just about marketing - it is also a meaningful opportunity to give back and a powerful statement about your organization’s role in the open source community. A healthy global conference is an important part of the geospatial open source ecosystem and strong sponsor support helps ensure users, developers, and contributors can connect and interact on improving the tools we all rely on.

The Boston Team is offering standard sponsor packages at the Supporter, Bronze and Silver levels. Our higher tiers – Diamond, Platinum and Gold – also include a variety of à la carte and customized benefits so that your investment in FOSS4G Boston 2017 can best meet your specific objectives for the conference.

**Comment by GuidoS** [comment]
ok, accepted your new language
