### ISSUE TITLE
wordsmithing under call for papers - type of story

### ISSUE THREAD

**Issue by cjacqz** [AvidGeo/foss4g2017-dev#24]
I had a little trouble distinguishing between the second and third bullets.  Seems like one is about the decision to adopt open source within an organization, and the other is about an individual application or use case...  

Suggested text: 

Type of Story 
- FOSS4G project updates and development, the traditional cornerstone of this conference
- How has open source geospatial worked for you – stories about adopting FOSS4G technology in your organization
- Stories about individual use cases and applications powered by FOSS4G technology
etc.

**Comment by GuidoS** [comment]
@cjacqz can you please have a look at the current page and resend with updates to your request as the page stands now.

**Comment by GuidoS** [comment]
I'm closing this as this whol page has been redone many times now.
