### ISSUE TITLE
On Sponsor page, list current sponsors as well as info on how to sponsor?

### ISSUE THREAD

**Issue by MassGIS** [AvidGeo/foss4g2017-dev#27]
In the Table of Contents the page is called Sponsorship instead of Sponsor and "the sponsors that make it happen".  However, the Sponsor page is more how to sponsor and doesn't list the sponsors (those are at the bottom of the main page currently)

**Comment by GuidoS** [comment]
This is going to be done in future iteration

**Comment by GuidoS** [comment]
I added the logos to the top of the page. This should suffice.
