### ISSUE TITLE
On iPhone SE "Keynote Speakers" overlaps a little with Holly's photo

### ISSUE THREAD

**Issue by MassGIS** [AvidGeo/foss4g2017-dev#34]
I have the smallest iPhone and things look pretty good, I just noticed this one thing.
Something about the layout.

It is OK in landscape mode, only appears in Portrait.

**Comment by GuidoS** [comment]
I had to shrink the view really tiny to make this happen, so I am feeling that this is a limited issue... that said, I did add a extra div with nbsp to resolve this.

**Comment by MassGIS** [comment]
Looks good now!
