### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by andyanderson** [AvidGeo/foss4g2017-dev#44]
Please change the Topics description to:

> Topics — one or more FOSS4G-focused subjects covered by your presentation:
> 
> • Development
> • Adoption
> • Use cases and applications
> • Research and design
> • Lessons learned: best practices, costs and benefits
> • History

The word FOSS4G is assumed and is distracting in its redundancy.
Also, a better word than “Software” is “Development”, as all of the talks will involve software.
“History” is an aspect that could show up in any of the theme areas.

Finally — it’s quite probable that most talks will address more than one of these areas. We should allow for that, unlike the themes that are fairly disjoint.

**Comment by andyanderson** [comment]
By the way, the “Topics” section is in there twice. I had moved my version after the Themes, since I view it as secondary, but it is also shorter so maybe it should be at the top and easy to skip past.

**Comment by GuidoS** [comment]
The updates for this page have been completed and are in sync with the CVent site.
