### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by andyanderson** [AvidGeo/foss4g2017-dev#46]
Please update the Theme description to:

----

#### FOSS4G Development
The traditional cornerstone of this conference, new and updated:
  * Tools 
  * Projects
  * Standards
  * Data

#### New Technologies
  Emerging trends that will have an impact on geospatial:
 * Drones
 * Internet of Things
 * Remote sensing
 * Machine learning
 * Big Data

#### Business
  Geospatial tools used in commerce:
  * Products
  * Business intelligence and logistics
  * Customer relations management and marketing

#### Government
  Local, state, and federal agencies are geographically rooted:
  * Policy and planning
  * Citizen engagement
  * Disaster management

#### The Sciences
  The natural and social sciences are often inherently geospatial, e.g.:
  * Climate and environment
  * Energy and natural resources
  * Agriculture and forestry
  * Biology
  * Public health
  * Archaeology

#### Education
  Teaching and using geospatial tools, in and out of the classroom:
  * Curricula
  * Community and Participatory GIS

----

Notes: I removed “Business Adoption” and “Local, state, and federal agency adoption and use” because they are redundant with the separately chosen topic of “Adoption”.

Added a couple more subheadings, modified others to make them less repetitive and more explanatory.

**Comment by GuidoS** [comment]
The list was synced with the information on the CVent, so we cannot change this list at this point.
