### ISSUE TITLE
Selection Process

### ISSUE THREAD

**Issue by andyanderson** [AvidGeo/foss4g2017-dev#47]
Please update the section Selection Process to the following:

---

The volunteer Program Committee will lead the presentation selection process but you, the attendees, will help through an open Community Voting process. The most popular presentations will be included in the program, and the Program Committee will select the remainder to provide a diversity of voices and content.

---

The first sentence in the current rendition, “We expect to have 200–250 talks selected through this Call for Presentations. ”, was moved to the top of the page to make clear what we are looking for. The second sentence, “ Keynote and invited presentations will round out the program. ” is not relevant to the selection process. We might want to say something about invited presentations on the main page, though, below the keynotes.

**Comment by GuidoS** [comment]
the content for this page has already been locked down for this page in production
