### ISSUE TITLE
Presentation Timeline

### ISSUE THREAD

**Issue by andyanderson** [AvidGeo/foss4g2017-dev#48]
Please update the title of the table “Timeline” to be “Presentation Timeline”. There will be a second Academic Paper Timeline following.

I think it’s helpful to have the conference date listed as the last item, too:

Monday – Friday
August 14 – 18	FOSS4G 2017 Conference

**Comment by GuidoS** [comment]
page is called "call for presentation" it sits next to process, so I think that timeline is appropriate without extra adjectives.

Again, the call for presentation timeline does not include the actual event, there is a whole other page for that. ;)
